services:
  nginx:
    build: ./client
    restart: unless-stopped
    ports:
      - 80:80 # host port : container port
      - 443:443
      # Containers can communicate on cadence_net using container port
      # Nginx service accessible outside docker environment via host port
    depends_on:
      - server
    networks:
      - cadence_net
    volumes:
      - /home/emma/actions-runner/ssl:/etc/nginx/ssl # Bind mounts actions runner ssl to container /etc/nginx/ssl
      - ./logs:/var/log/nginx
  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - ~/actions-runner/env/.env
    volumes:
      - ~/actions-runner/env/.env:/.env
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://musicbrainz:musicbrainz@db:5432/musicbrainz_db
    networks:
      - cadence_net
    healthcheck: # Check server is running before running nginx container
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  cadence_net:
    external: true
