services:
  cadence-server:
    build: ./server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://musicbrainz:musicbrainz@host.docker.internal:5432/musicbrainz_db
    networks:
      - cadence_net

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"  
    networks:
      - cadence_net

networks:
  cadence_net:
    driver: bridge


